### ISSUE TITLE
FOP.py cannot recognise some AdGuard modifiers

### ISSUE THREAD

**Issue by Alex-302** [PolishFiltersTeam/ScriptsPlayground#1]
`extension`
`jsinject`
`stealth`
`content`
and
`app=`
`replace=`
`protobuf=`
`cookie=`
and
`"redirect=noeval.js" used on the filter "||strm.yandex.ru^$redirect=noeval.js,script" is not recognised by FOP`

**Comment by hawkeye116477** [comment]
@Alex-302 I didn't see `cookie`, `protobuf` and `redirect=noeval.js` on documentation (https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters).

**Comment by Alex-302** [comment]
But they are exists :).

---

Some examples:
- `$cookie` https://github.com/AdguardTeam/AdguardBrowserExtension/issues/961
```
||moniteurautomobile.be^$cookie=/_dc_gtm_|_gat_/
||vc.ru/$cookie=fingerprint
||vc.ru^$cookie=adblock-state
||vc.ru^$cookie=/^__io/
||vc.ru^$cookie=/^io_/
```
- `$protobuf`
```
|googleapis.com/youtubei/v1/player$protobuf=48841103|63112829|23|25
||googleapis.com/youtubei/v1/search?$important,protobuf=73920376
||googleapis.com/youtubei/v1/search?$protobuf=73920376
```
- `redirect=noeval.js`
https://github.com/AdguardTeam/Scriptlets#-redirect-resources-compatibility-table
- `$app`
```
||graph.facebook.com^$app=com.spacegame.basic3|com.spacegame.basic5|com.spacegame.basic7
||ad.bench.utorrent.com^$app=uTorrent.exe
```

**Comment by Alex-302** [comment]
Values of `$cookie`, `$protobuf`, `$replace` rules should not be changed(at the moment `_` is conterted to `-`)

**Comment by hawkeye116477** [comment]
@Alex-302 Ok, so it's one string `48841103|63112829|23|25`, not multiple strings separated by pipe?
`||googleapis.com/youtubei/v1/player$protobuf=48841103|63112829|23|25`

**Comment by hawkeye116477** [comment]
@Alex-302 Ok, added.

**Comment by hawkeye116477** [comment]
Some other AdGuard scriptlets are missing, for now I didn't add it, cuz they only works for internal AdGuard filters made by AdGuard or for external, but „trusted" must be checked. I though that if scriptlets come to AdGuard at least some will not require that thing...
