### ISSUE TITLE
Some script malform `redirect`/`redirect-rule` if have `_`?

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/ScriptsPlayground#18]
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/dd11337945ea4a6dfffce0d0bc31c8e6cd87575b - correct
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/commit/7c5312914add2c56486e0946e42bcf3c676110aa - malformed

All names with `_`:

AdGuard | uBO | Adblock Plus
-- | -- | --
amazon-apstag | amazon_apstag.js |  
google-analytics | google-analytics_analytics.js |  
google-analytics-ga | google-analytics_ga.js |  
googlesyndication-adsbygoogle | googlesyndication_adsbygoogle.js |  
googletagservices-gpt | googletagservices_gpt.js |  
scorecardresearch-beacon | scorecardresearch_beacon.js |  
  | addthis_widget.js |  
  | amazon_ads.js |  
  | ampproject_v0.js |  
  | doubleclick_instream_ad_status.js |  
  | google-analytics_cx_api.js |  
  | google-analytics_inpage_linkid.js |  
  | ligatus_angular-tag.js |  
  | mxpnl_mixpanel.js |

**Comment by hawkeye116477** [comment]
To FOP zamienia => https://github.com/FiltersHeroes/ScriptsPlayground/blob/adcf76a7900df7d87bbeb3cf170a90b497a66f09/scripts/FOP_FH.py#L263 i jak się okazuje, to dodał oryginalny autor, czyli Michael. Nie wiem w jakim celu to było, ale wydaje się zbędne.
