### ISSUE TITLE
Wiki dla skryptów?

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/ScriptsPlayground#2]
Nie wiem czy każdemu helper w python będzie odpowiadał:

```log
Traceback (most recent call last):
  File "C:\Users\Krystian\Downloads\scripts\GDE.py", line 171, in <module>
    extractDomains()
  File "C:\Users\Krystian\Downloads\scripts\GDE.py", line 82, in extractDomains
    print(separator.join(final_links))
UnboundLocalError: local variable 'separator' referenced before assignment
```

Nie wiem czy to nie wina locales w złej lokalizacji. Albo jakiś if z pop-upem, że pole jest wymagane?

**Comment by hawkeye116477** [comment]
@krystian3w Podaj więcej szczegółów, co chciałeś zrobić, co wpisałeś tam.

**Comment by krystian3w** [comment]
Domyślną konfigurację i z listy nie wybrałem przecinka - a.k.a:
* https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1731,
*  https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1732.

Jak się da; to w wersji "`v1.2.2.2`" zrobić, by nie pracował skrypt, aż nie wybierzesz z listy przecinka lub pipe.

A wiki by nie szukać "dniami" jak zrobić instalacje "masowo" (lub każde z osobna):

```css
pip install certifi urllib3 beautifulsoup4 tldextract pysimplegui appdirs html5lib
```

skoro nie można zrobić testu czy ktoś ma najnowszy `pip` i co zapomniał zainstalować.

**Comment by hawkeye116477** [comment]
> Jak się da; to w wersji "v1.2.2.2" zrobić, by nie pracował skrypt, aż nie wybierzesz z listy przecinka lub pipe.

Ale od razu po odpaleniu jest coś tam wybrane, no chyba że usunąłeś backspacem :smiley:

**Comment by krystian3w** [comment]
# жопа

U mnie pusto, nie klikam backspace (a raczej trzeba by po każdym uruchomieniu):

![obraz](https://user-images.githubusercontent.com/35370833/70461091-27aa5380-1ab8-11ea-8bc3-84a435daea67.png) |
--- |

Nawet kursor siedzi w pierwszym polu a nie 3.

**Comment by hawkeye116477** [comment]
To dziwne, sprawdzę potem na Windzie. Tak czy siak, trzeba będzie zablokować edycję w combo boxie, dziwne, że domyślnie zrobili, że można edytować.

Odnośnie https://github.com/PolishFiltersTeam/ScriptsPlayground/issues/2#issuecomment-563363372, to wygląda na to, że po aktualizacji pysimplegui coś pozmieniali, a ja oczywiście nie dostałem powiadomienia o nowej wersji, bo najwyraźniej nie było komu zaktualizować pakietu w aur => https://aur.archlinux.org/packages/python-pysimplegui/.

**Comment by hawkeye116477** [comment]
@krystian3w Odnośnie https://github.com/PolishFiltersTeam/ScriptsPlayground/issues/2#issuecomment-563363372, to wygląda na to, że po aktualizacji pysimplegui coś pozmieniali, a ja oczywiście nie dostałem powiadomienia o nowej wersji, bo najwyraźniej nie było komu zaktualizować pakietu w aur => https://aur.archlinux.org/packages/python-pysimplegui/.

**Comment by hawkeye116477** [comment]
@krystian3w Wygląda na to, że dodali też motywy albo ja wcześniej ich nie zauważyłem. Który wybierasz? Dla Linuxa raczej pozostawię systemowy, by każdy sobie ustawił jaki chce.
<img src="https://user-images.githubusercontent.com/46163555/70382042-796da500-1923-11ea-8432-80d08cd5f503.jpg">

**Comment by krystian3w** [comment]
To jest ten `look` ... `Dark Blue 3`?

**Comment by hawkeye116477** [comment]
@krystian3w Tak

**Comment by hawkeye116477** [comment]
@krystian3w Nie powiedziałeś co chcesz, więc wybrałem za ciebie i trochę zmodyfikowałem motyw, zrobiłem podobny do mojego systemowego Breath Dark. 
Wrzuciłem już nową wersję, potem może dorobię jeszcze exe dla Windy => `https://pysimplegui.readthedocs.io/en/latest/#windows-programs-that-look-like-windows-programs`, dzięki czemu jak masz Windowsa, to tylko odpalisz exe i wtedy nie trzeba ręcznie instalować pythona i modułów, więc obejdzie się bez wiki, a Linuksiarze sobie poradzą :smile:

**Comment by hawkeye116477** [comment]
@krystian3w Jednak zrobiłem inaczej z uwagi na to, że tamtym sposobem wolniej się odpala, niby jest lepsza alternatywa, ale dodaje to nieco więcej DLLów i musiałbym szukać i pododawać teksty licencyjne do każdego, nie chciało mi się, więc zrobiłem po prostu zipa z listą wymaganych modułów w txt, tak więc wystarczy jedynie zainstalować pythona i wykonać polecenie:

 `pip install -r sciezka/requirements.txt`

**Comment by krystian3w** [comment]
Mam nowy bug, skrypt gubi się jak Python jest z MS Store:

`AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\Local\GroupsDomainsExtractor\groups.ini`

zastanawiam się, czy da się przechwycić akcje, że Python zapisuje plik zupełnie gdzie indziej:
"`Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\Local\`".

**Comment by hawkeye116477** [comment]
Cóż obecnie jest to `user_config_dir()/GroupsDomainsExtractor`, a `user_config_dir()` jest z biblioteki https://github.com/ActiveState/appdirs. Tak więc to chyba raczej sprawa do nich...
