### ISSUE TITLE
Manipulated recursion DNS 

### ISSUE THREAD

**Issue by spirillen** [PolishFiltersTeam/ScriptsPlayground#29]
Just to let you know, I rather vastly spotted these DNS recurser's as unreliable, as they do response with manipulated data + they do not perform own lookup's but solely relays other third party data.

I suggest you change to 9.9.9.10 & 149.112.112.10 as they do their own unfiltered lookup (and they offers full privacy)

https://github.com/FiltersHeroes/ScriptsPlayground/blob/894702b68d26c4449b6f07b2ce0cb15f11049c49/scripts/ECODFF.py#L80

**Comment by hawkeye116477** [comment]
Well, in the past as first wanted to try Cloudflare DNSes, cuz I'm not a big fan of G, but there were problems with receiving responses, so I changed that.  However didn't know that there is something other good which isn't blocking websites. I'll try it, thanks.
