### ISSUE TITLE
FOP - malform a few network filters

### ISSUE THREAD

**Issue by realodix** [PolishFiltersTeam/ScriptsPlayground#8]
FOP 3.19

**Step**
- `_foobar.$domain=~example.com`
- Run FOP v3.19

**Expected**
`_foobar.$domain=~example.com`

**Actual**
`_foobar.$domain= ~ example.com`

**Comment by krystian3w** [comment]
Interestingly, we have a little similar filter and there was no bug:
```
||dlastudenta.pl/cookie/cookie_set.js$script,~third-party,domain=~www.dlastudenta.pl
||dlastudenta.pl/cookie/upd/$~third-party,xmlhttprequest,domain=~www.dlastudenta.pl
```

I suppose bugged here: https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/260de4390a5b6b8f03d3fab2ab307ecabdcc7481/scripts/FOP.py#L41

or in: https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/260de4390a5b6b8f03d3fab2ab307ecabdcc7481/scripts/FOP.py#L189-L220

**Comment by ghost** [comment]
Tu chyba powinny być gwiazdki:

https://github.com/PolishFiltersTeam/ScriptsPlayground/blob/260de4390a5b6b8f03d3fab2ab307ecabdcc7481/scripts/FOP.py#L424-L431

`filtertext[0] == ""` -> `filtertext[0] == "*"`?
`filtertext[-1] == ""` -> `filtertext[-1] == "*"`?

Kiedyś były: <https://github.com/adblock-thai/thai-ads-filter/blame/bf2d67c0afd2777cbd2f06f0613ec03a10c8bf58/FOP.py#L392-L397>, https://github.com/adblock-thai/thai-ads-filter/commit/017f1473421f8d707d5c5ecc0d9ecccda00490fc

**Comment by ghost** [comment]
Does it happen with `/_foobar.$domain=~example.com`? 

If not,

`_foobar.$domain=~example.com` [is matching](https://regex101.com/r/z7CqyY/1) `ELEMENTPATTERN` and filter is run through `elementtidy`.


`x ~ y` - beautified syntax for general sibling combinator.

***

Broken here: https://github.com/PolishFiltersTeam/ScriptsPlayground/commit/aa89c9c4a8b5f9dc690caf6452c58709be0e9eba ?

**Comment by krystian3w** [comment]
>Does it happen with  `/_foobar.$domain=~example.com`?

No.


---

Also:
* it helps: `_foobar.$domain=~example.com|example.org`

* and: `_foobar.$domain=~example.com|~example.org`

--- 

Idea with  beautified CSS path may match.

**Comment by krystian3w** [comment]
@hawkeye116477 this is good:

```regex
^([^\/\*\|\@\"\!]*?)(\$\@?\$?\??#|##\@?\$|#\@?#?\+?)(.*)$
```

<table><tr><td>

* `$$`

   * `$@$`

</td><td>

* `##`
   * `#@#`

</td><td>

* `#?#`
   *  `#@#`
   * `#@?#`

</td><td>

* `#$#`
   * `#@$#`

</td><td>

* `#$?#`
   * `#@$?#`

</td><td>

* `#%#`
   * `#@%#`

</td>

</tr><tr><td> html filtering </td><td> simple CSS </td><td> ExtendedCSS / procedural filter</td><td> CSS filter  <br><br> (or ABP scriptlet / snippet) </td><td> CSS inline filter </td><td> AdGuard scriptlet </td></tr>


</table>



❓

**Comment by hawkeye116477** [comment]
Maybe I will see all after holidays :smile:

**Comment by hawkeye116477** [comment]
@krystian3w It's wrong, cuz html filtering can be without hash, for example `example.org$$script[data-src="banner"]`.
